Irregular, regular timeseries, testing fixes, time span fix, and sec granularity
HydrologicEngineeringCenter/hec-dss-python pull request #59
Opened 2024-12-11 20:01 UTC by oskarhurst

Pull request include added functionality and bug fixes to the irregular and regular time series classes. It also include adding additionally testing to pytests for regular time Series and other bugs. These other bugs include added second granularity to all timeseries objects, allowing used to get the range of date in a timeseries, allowing used to get all data help with in a path with out knowing the start and end time, and fixing miss representation of Julian times.

2024-12-11 22:37 UTC, ktarbet requested changes

2024-12-11 22:37 UTC, ktarbet commented on src/hecdss/dateconverter.py
> +    def date_time_from_julian_second(time_julian, seconds_julian):
@oskarhurst  suggests using method below passing in argument of 1 for  time_granularity_seconds.

2024-12-11 22:37 UTC, ktarbet commented on src/hecdss/dateconverter.py
> +            if time_granularity_seconds == 1:  # 60 seconds per minute
```suggestion
            if time_granularity_seconds == 1:  # 1 second
```

2024-12-11 22:37 UTC, ktarbet commented on src/hecdss/dateconverter.py
>              if time_granularity_seconds == 3600:  # 600 seconds per hour
```suggestion
            if time_granularity_seconds == 3600:  # 3600 seconds per hour
```

2024-12-11 22:37 UTC, ktarbet commented on src/hecdss/hecdss.py
> +                60,
```suggestion
                60,    # @oskarhurst  suggests this isn't always 60 ,  might be 1 for example
```

2024-12-11 22:37 UTC, ktarbet commented on src/hecdss/lib/hecdss_orgi.dll
please remove DLL

2024-12-11 22:37 UTC, ktarbet commented on tests/test_regular_timeseries.py
> +        #dss = HecDss("C:/Users/q0hecoah/Documents/data/examples-all-data-types.dss")
```suggestion
```

2024-12-12 17:08 UTC, ktarbet commented on tests/data/sample7.dss
Does this file need to be included?  or can it be reverted since DSS/DSSVue modifies files whenever they are opened.

2024-12-12 22:47 UTC, ktarbet commented on src/hecdss/dateconverter.py
> +    def date_time_from_julian_second(time_julian, seconds_julian):
I think there are zero references to this method now? so It can be deleted.

2024-12-12 22:48 UTC, ktarbet commented on src/hecdss/dateconverter.py
>              baseDateTime =datetime(1900,1,1)- timedelta(days=1)     #datetime.fromtimestamp(julian_base_date)
```suggestion
            baseDateTime =datetime(1900,1,1)- timedelta(days=1) 
```

2024-12-12 23:19 UTC, ktarbet commented on src/hecdss/hecdss.py
> +            newStartDateTime, newEndDateTime = self._get_date_time_range(pathname, 1)
Can this code could be simplified. would something like this work?

```python
def _get_timeseries(self, pathname, startDateTime, endDateTime):
    if not startDateTime or not endDateTime:
        newStartDateTime, newEndDateTime = self._get_date_time_range(pathname, 1)

        if not startDateTime:
            startDateTime = newStartDateTime
        if not endDateTime:
            endDateTime = newEndDateTime

    startDate = startDateTime.strftime("%d%b%Y")
    startTime = startDateTime.strftime("%H:%M:%S")
    endDate = endDateTime.strftime("%d%b%Y")
    endTime = endDateTime.strftime("%H:%M:%S")

2024-12-13 00:33 UTC, oskarhurst commented on src/hecdss/hecdss.py
> +            newStartDateTime, newEndDateTime = self._get_date_time_range(pathname, 1)
yes this would work thank you.

2024-12-13 16:14 UTC, ktarbet approved these changes

2024-12-13 17:47 UTC, merged